# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.
configuration: Release
platform: Any CPU
install:
  # by default, all script lines are interpreted as batch
  #- echo This is batch
  # to run script as a PowerShell command prepend it with ps:
  #- ps: Write-Host 'This is PowerShell'
  ps: Set-Culture fr-FR

build:
  # MSBuild verbosity level
  #verbosity: quiet|minimal|normal|detailed
  verbosity: minimal
  parallel: true  
