configuration: Release
platform: Any CPU
install:
  # by default, all script lines are interpreted as batch
  #- echo This is batch
  # to run script as a PowerShell command prepend it with ps:
  #- ps: Write-Host 'This is PowerShell'
  ps: Set-Culture fr-FR

build:
  verbosity: minimal
  parallel: true  

  # MSBuild verbosity level
  #verbosity: quiet|minimal|normal|detailed
